### ISSUE TITLE
Provide guzzle parameters to be configurable in behat.yml

### ISSUE THREAD

**Issue by dziamid** [Behat/MinkExtension#14]
There seems to be no easy way to configure guzzle parameters in behat.yml

I need a way to set curl.CURLOPT_SSL_VERIFYPEER = false to be able to test https pages on local machine.

**Comment by uptownhr** [comment]
I'm having the same issue, doesn't appear that parameters are making it through. 

```
"behat/mink": "^1.7",
"behat/mink-goutte-driver": "^1.2",
"behat/behat": "~3.0.4",
"behat/mink-extension": "^2.1"
```

**Comment by spagu** [comment]
any workaround already ?
