### ISSUE TITLE
Official documentation is out of date

### ISSUE THREAD

**Issue by shadowhand** [Behat/MinkExtension#146]
It still recommends using `Behat\MinkExtension\Extension`, but this will cause an error:

```
[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]
`Behat\MinkExtension\Extension` extension file or class could not be located.
```

Using `Behat\MinkExtension` as per #142 also does not work:

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
Unrecognized options "context" under "testwork" 
```

How does one use Mink with Behat 3.0?!

cc @rjmackay

**Comment by webbj74** [comment]
Noting that the current docs are actually at http://docs.behat.org/en/latest/ even though behat.org still defaults to v2.5 docs in most places.

**Comment by aik099** [comment]
Behat docs point to v2.5 for BC reasons unfortunately.
