### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by svemir** [Behat/MinkExtension#161]
I am assuming this is due to behat docs being reorganized, since some links redirect to files on github already. Perhaps the two broken links on the main page of MinExtension should redirect to https://github.com/Behat/MinkExtension/blob/master/doc/index.rst

**Comment by stof** [comment]
The readme link has been fixed in https://github.com/Behat/MinkExtension/commit/84ee4edd514d49fc6705727e5ecbaf93bf2aad88
