### ISSUE TITLE
get screenhot on failure - showFailedStepScreenshot

### ISSUE THREAD

**Issue by fonsecas72** [Behat/MinkExtension#170]
Hi, 
When some test fail I would like to have some screenshot of this (I use mostly selenium2 webdriver to test my applications so I can do that).
I know I can add a @AfterStep tag to a function and take the screenshot there but I don't like this solution.
I wanted to know what do you advise.
Should I add some listener like the "showFailedStepResponse" to this extension? (a showFailedStepScreenshot ?)

Or do you recommend something else?
Thanks

**Comment by PatchRanger** [comment]
I second this: looks like it is a desired common feature rather than space for custom development.

**Comment by spolischook** [comment]
JFYI, not all drivers support the screenshot.
What wrong with beforeScenario hook or a custom listener?

**Comment by PatchRanger** [comment]
@spolischook Thank you for response. Nothing's wrong, I just thought it could be done in a more general manner. If not all drivers support screenshots, I guess nothing left other than proposed by you: either beforeScenario hook or a custom listener.

**Comment by PatchRanger** [comment]
Looks related: https://gist.github.com/jk/6422163 .

**Comment by spolischook** [comment]
It would be great to have some interfaces and flow how to save artifacts after fail.
We have a lot of data that should be stored somewhere (e.g. by FTP) and also we should have link to artifacts in console output.
Very rough implementation https://github.com/oroinc/platform/tree/94c3e11d8baa5e2966033b10b6632571a9532ac4/src/Oro/Bundle/TestFrameworkBundle/Behat/Artifacts
