### ISSUE TITLE
user not allowed to set tags sent to selenium

### ISSUE THREAD

**Issue by gggeek** [Behat/MinkExtension#184]
In the selenium2 factory, the 'tags' field is create by an array_merge, which favours the auto-calculated tags over the tags set by the user (note that in fact a user can not set tags explicitly in the capabilities settings field, but he can set them in the extra_capabilities field).

It makes more sense imho to let the user override, if he wants, the capabilities which are auto-guessed by the code.

Note that this does not apply to build number and tunnel_identifier as those are allowed in the settings schema

**Comment by aik099** [comment]
:+1:

**Comment by stof** [comment]
Fixed in #185
