### ISSUE TITLE
Speed up tests with PhantomJS

### ISSUE THREAD

**Issue by KuenzelIT** [Behat/MinkExtension#192]
Hey,
I'm looking for some people who can explain to me, why my tests are so damn slow and how I can speed them up.

I'm using Behat+Mink, the selenium2 driver and PhantomJS with GhostDriver to run tests with Javascript. I have a simple and mostly empty page with two input fields "name" and "password". Just filling these two fields in my test needs 35 seconds. Is this normal and is there any way to speed this up?

There is no Javascript on this site. I just used a blank Laravel project to see if the test was slow because of the real site I'm testing (which has javascript...).

If I'm wrong with my question here, please tell me the right direction.

My behat.yml:
~~~
#behat.yml
default:
  autoload:
      '': %paths.base%/app/tests/acceptance/bootstrap
  suites:
      default:
          paths:
              - %paths.base%/app/tests/acceptance
  extensions:
      Behat\MinkExtension:
          base_url: http://localhost/BehatPhantomJS/public
          goutte: ~
          selenium2: ~
~~~

And my feature:
~~~
@javascript
Feature: testing
  Scenario: testing
    Given I am on "/"
    Then I should see "testing"
    Then I fill in "name" with "test"
    Then I fill in "password" with "test2"
~~~

And my composer require-dev:
~~~
"require-dev": {
		"behat/mink": "~1.6",
		"behat/mink-goutte-driver": "~1.1",
		"behat/behat": "~3.0",
		"behat/mink-extension": "~2.0",
		"behat/mink-selenium2-driver": "~1.2"
	},
~~~

Thanks!

**Comment by stof** [comment]
If there is no JS, remove the ``@javascript`` tag so that the scenario runs in Goutte rather than the Selenium2Driver. It will be much faster. The WebDriver protocol is slow. There is nothing we can do against that AFAIK.

**Comment by aik099** [comment]
In my experience, when using WebDriver protocol, the PhantomJS is slower than Selenium. But fulling 2 input fields shouldn't take 35 seconds for sure. If that would be the case, then MinkSelenium2Driver would take forever to run on Travis CI.

**Comment by KuenzelIT** [comment]
Unfortunately it is 35 seconds. Is there any alternative for PhantomJS, which doesn't require Java and isn't Zombie? If not, I'm just going to try it with Selenium and see, if it's as slow as PhantomJS.

**Comment by KuenzelIT** [comment]
I tested it with Selenium now and yes it's a lot faster. It took 4 seconds for that little example and isn't even headless. Same example takes 40 seconds with PhantomJS.

Still, I'd like to know, what the problem is with Phantom. Does anyone have an idea?

**Comment by aik099** [comment]
Probably a bug in PhantomJS. I recommend you recording WebDriver commands you've made and posting an issue to GHost driver repo.

**Comment by KuenzelIT** [comment]
Alright, thank you!

**Comment by wheelsandcogs** [comment]
@KuenzelIT did you get anywhere with this? I'm experiencing the same issue with my small suite - selenium + phantomjs (7 minutes) is much slower than selenium + firefox (5 minutes) or selenium + chromedriver (1 minute).

One of the main points of PhantomJS is that it's supposed to be faster than running a full browser...

**Comment by aik099** [comment]
Unfortunately for me the PhantomJS was always slower even, than using Selenium+xvfb, which actually makes it useless.

**Comment by stof** [comment]
I think that the PhantomJS webdriver implementation is not optimized properly, compared to other ways to use PhantomJS.

**Comment by wheelsandcogs** [comment]
I thought I'd try the zombie driver just to compare and it took 14 minutes! I think I'll stick with chromedriver for now.

**Comment by KuenzelIT** [comment]
Nope, didn't get any better and I completely switched to selenium, which is about 10 times faster.
