### ISSUE TITLE
Allow dynamic registration of drivers

### ISSUE THREAD

**Issue by gggeek** [Behat/MinkExtension#203]
I might be misunderstanding the code, but it seems that the extension allows me to create custom sessions, but the list of drivers to implement them is hardcoded.

Why do I want to implement my custom driver? For any number of reasons, the one at hand being that I want to subclass the Selenium2 driver to take control of the chain of 'service injection' (...) which in the end gives me an object from php-webdriver into which I can not set custom curl options ( see discussion here: https://github.com/instaclick/php-webdriver/issues/51 )

**Comment by stof** [comment]
Other Behat extensions can register their own drivers. This is what the Symfony2Extension is doing for instance: https://github.com/Behat/Symfony2Extension/blob/8263a4760c02ab6b6e29751c5fb8a28f44796d52/src/Behat/Symfony2Extension/ServiceContainer/Symfony2Extension.php#L51

**Comment by gggeek** [comment]
Aha! Thanks @stof

**Comment by gggeek** [comment]
For the record: 1300 lines of code, most of which I had to duplicate, just to be able to inject 1 CURLOPT parameter.

Color me uninmpressed with FINAL, private and using classes instead of interfaces in method declarations...

**Comment by aik099** [comment]
That kind of code: https://github.com/Behat/Symfony2Extension/blob/8263a4760c02ab6b6e29751c5fb8a28f44796d52/src/Behat/Symfony2Extension/ServiceContainer/Symfony2Extension.php#L68-L96 ?

**Comment by gggeek** [comment]
@aik099 https://github.com/Behat/Symfony2Extension/blob/8263a4760c02ab6b6e29751c5fb8a28f44796d52/src/Behat/Symfony2Extension/ServiceContainer/Symfony2Extension.php#L51 and this: https://gist.github.com/gggeek/ca746db7b77048a1be8e (note that it is used for saucelabs, but that is just a selenium subdriver)
