### ISSUE TITLE
Invalid detection of false value in JSON

### ISSUE THREAD

**Issue by klinkiap** [Behat/MinkExtension#214]
There is a bug in detection of false value. 

I have a step: `And the JSON node "is_completed" should be equal to "false"`
and I'm getting this error: `The node value is 'false' (Exception)`

I tried  `And the JSON node "is_completed" should contain "false" ` as well but it is not working either. 

True value works fine.

**Comment by stof** [comment]
There is no such step in MinkExtension. Please open the issue on the repo providing the JSON assertions
