### ISSUE TITLE
Switch to main window after session reset

### ISSUE THREAD

**Issue by aik099** [Behat/MinkExtension#220]
I'm not 100% certain, but this might be a problem.

Consider 2 scenarios:

1. Scenario 1:
 * go to url
 * click on link
 * popup opens
2. Scenario 2:
 * go to url
 * check text on the page

I'm assuming same Mink session is used for both scenarios, but is soft-reset (cookies removed) after scenario ends. Then "Scenario 2" would be started in popup window opened by "Scenario 1".

If this creates problem for somebody, then I suggest (in the MinkExtension) to also call `$session->switchToWindow(null);` to switch to 1st opened window in the session, which is usually main window.

**Comment by stof** [comment]
shouldn't this be handled at the driver level when resetting it though ?

**Comment by aik099** [comment]
Yes, drivers, that support window manipulations can call `->switchToWindow(null);` inside their `reset` method. Drivers that don't support it just stay as they are.

**Comment by aik099** [comment]
I've created corresponding tasks in each relevant driver repo.

**Comment by aik099** [comment]
Closing because all related tasks are closed.
