### ISSUE TITLE
Override method cannot be executed

### ISSUE THREAD

**Issue by nguyentienlong** [Behat/MinkExtension#221]
I am using behat 3.0.15, behat/mink: 1.7
I overrided a method of MinkContext like this:
--
```php
class XContext extends MinkContext
{
    //some method
   
    //override method assertUrlRegExp (MinkContext class)
    /**
     * Checks, that current page PATH matches regular expression.
     *
     * @Then /^the (?i)url(?-i) should match (?P<pattern>"(?:[^"]|\\")*")$/
     */
    public function assertUrlRegExp($pattern)
    {
        var_dump($this->getSession()->getCurrentUrl());
    }
}
````
When I run vendor/bin/behat - it threw this error:
```Step "/^the (?i)url(?-i) should match (?P<pattern>"(?:[^"]|\\")*")$/" is already defined in Tests\XContext::assertUrlRegExp()```
**So, the question is that "can I override a method with annotation @Then  in MinkContext " ?**

**Comment by aik099** [comment]
Haven't you by accident included both feature files (XContext and MinkContext) in your test suite?

**Comment by nguyentienlong** [comment]
@aik099 thank you for your feedback. I resolve this issue.
