### ISSUE TITLE
$this->getSession()->getWindowNames()

### ISSUE THREAD

**Issue by ScreamZ** [Behat/MinkExtension#223]
Hi,

I'm looking for this feature present in the Mink driver but apparently not in the extension :

$this->getSession()->getWindowNames()

Can we include it ?

Thanks

**Comment by aik099** [comment]
Code you mentioned works already. What do you mean then by not present in extension?

**Comment by ScreamZ** [comment]
I'm using those depencies : 

"require-dev": {
        "behat/behat": "3.0.*",
        "behat/symfony2-extension": "2.0.*",
        "behat/sahi-client": "dev-master as 1.1.1",
        "behat/mink-extension": "*",
        "behat/mink-goutte-driver": "*",
        "behat/mink-selenium-driver": "*",
        "behat/mink-sahi-driver": "*",
        "behat/mink-selenium2-driver": "*",
        "ezsystems/behatbundle": "~5.4",

and I can't find the method getWindowNames() in the vendor/behat/mink/src/Behat/Mink/Driver/DriverInterface.php file.

So i'm looking for a way to get it...

Maybe I'm not looking in the good way, thanks...

**Comment by aik099** [comment]
What are the actually used library versions? You can get them by running `composer show -i` command.

I'm suspecting that you're using some old Mink version (e.g. 1.5), that doesn't have that method.

**Comment by aik099** [comment]
Also please don't use `*` as version, because this way you'll never know what version you'll get.

**Comment by ScreamZ** [comment]
behat/behat                                  v3.0.15            Scenario-oriented BDD framework for PHP 5.3
    behat/gherkin                                v4.3.0             Gherkin DSL parser for PHP 5.3
    behat/mink                                   v1.5.0             Web acceptance testing framework for PHP 5.3
    behat/mink-browserkit-driver                 v1.1.0             Symfony2 BrowserKit driver for Mink framework
behat/mink-extension                         v2.1.0             Mink extension for Behat
behat/mink-goutte-driver                     v1.0.9             Goutte driver for Mink framework
behat/mink-sahi-driver                       v1.1.0             Sahi.JS driver for Mink framework
behat/mink-selenium-driver                   v1.1.0             Selenium driver for Mink framework
behat/mink-selenium2-driver                  v1.1.1             Selenium2 (WebDriver) driver for Mink framework
behat/sahi-client                            dev-master ce7bfa7 Sahi.js client for PHP 5.3
behat/symfony2-extension                     v2.0.0             Symfony2 framework extension for Behat
behat/transliterator                         v1.0.1             String transliterator

Seems to be right, Composer took the minimum required

**Comment by aik099** [comment]
I recommend specifying exact version of each library at the moment and prepend `^` in front. For Mink that would be `^1.7`. That will ensure that you'll also get `1.7.1` and `1.7.3` automatically, but not `1.8`.

**Comment by aik099** [comment]
And you really need all of Mink drivers?

**Comment by ScreamZ** [comment]
I'll try, it's my company pre-packaged composer.json ,i'll make an internal pull request if it works. Thanks I keep you informed

**Comment by stof** [comment]
@aik099 your comment is wrong. ``^1.7`` allows anything up to the next major version

**Comment by aik099** [comment]
Any `1.x.x` release, but larger or equals to `1.7.0` then? The `~1.7` does the same?

**Comment by stof** [comment]
@aik099 yes it does. but ``^1.7.0`` still goes up to 2.0 (excluded) while ``~1.7.0`` only goes up to 1.8 (excluded)

**Comment by ScreamZ** [comment]
It's ok boys, It was the version 1.5.x of Mink that had to be >= 1.7

So much thanks.
