### ISSUE TITLE
Escaping issues with xpathLiteral

### ISSUE THREAD

**Issue by rslid** [Behat/MinkExtension#232]
Hello,

First I should mention that my coding skills are not great (yet) but this issue is really strange and I can't figure it out in last 2 hours... I am getting value with :arg and I try to escape it with 
    $this->getSession()->getSelectorsHandler()->xpathLiteral($text); 
but I'm getting strange error in the console
    missing ; before statement
I checked everything and all semicolons are properly set. Testing string is ~!@#$%^&*()_+ :{}?|-= æøåÆØÅ,./'[]\

**Comment by aik099** [comment]
Maybe issue with encoding used isn't UTF-8.

**Comment by rslid** [comment]
Actually the issue is with single quote and was caused by custom js which was added. Not a mink issue at all. Sorry for the thread...
