### ISSUE TITLE
Use getOuterHtml() method in elementContains() method

### ISSUE THREAD

**Issue by roukmoute** [Behat/MinkExtension#245]
Hi !

I wanted to use the method "assertElementContains" but it uses internally the getHTML() method.
I do not understand why.
The example provides:  `Then the "body" element should contain "style=\"color:black;\""`
I understand that he will be able to find `style="color:black;"` in the `body` tag.

But with the use of getHTML() that doesn't work.
Should be used getOuterHtml().

Is it correct ?

**Comment by aik099** [comment]
This works as it should: check only contents of the tag, not it's attributes.

**Comment by stof** [comment]
The body does not contain itself. You should write your own assertion if you want to check attributes

**Comment by roukmoute** [comment]
Ok thanks 👌
