### ISSUE TITLE
Allow manual session construction

### ISSUE THREAD

**Issue by aik099** [Behat/MinkExtension#251]
Right now new `Session` class instance creation is hidden within `Mink::getSession` class and there is no way affect created session in any way, e.g. add new selectors handler.

Any idea how to make it configurable.

Related Issue: https://github.com/minkphp/Mink/issues/706

**Comment by stof** [comment]
Changing the dependencies should be done by altering the DIC used by Behat IMO

**Comment by aik099** [comment]
Since session is not created directly like `new Session()`, but using `Mink::getSession` method (which IMO should have been part of MinkExtension, rather than Mink) it is currently impossible to delegate session building role to anybody else.

**Comment by stof** [comment]
@aik099 sessions are not created by ``Mink::getSession``. They are managed in the DIC. The Mink object does not know how to instantiate a Session. It receives them in its constructor (or through ``registerSession``)

**Comment by aik099** [comment]
Ah, I see it now in https://github.com/Behat/MinkExtension/blob/master/src/Behat/MinkExtension/ServiceContainer/MinkExtension.php#L236 line.

Then I guess https://github.com/Behat/MinkExtension/blob/master/src/Behat/MinkExtension/ServiceContainer/MinkExtension.php#L232-L235 should be made configurable somehow.

**Comment by stof** [comment]
@aik099 Behat extensions are able to manipulate the DIC (they are compiler passes, so they can alter what they want). This allow them to manipulate service definitions if they need it

**Comment by aik099** [comment]
It seems, that changing definition for `mink.selectors_handler` would be enough to have custom selector handler added.
