### ISSUE TITLE
Use a more recent version of mink in composer.json

### ISSUE THREAD

**Issue by DWmodem** [Behat/MinkExtension#279]
Currently in `composer.json` there is this:
```javascript
    "require": {
        "php":          ">=5.3.2",
        "behat/behat":  "~3.0,>=3.0.5",
        "behat/mink":   "~1.5",
        "symfony/config": "~2.2|~3.0"
    },
```
The version of mink used here is ~1.5. The last change made to this dates back to 2014.
Would there be a chance to:

**a)** Use `minkphp/mink` instead ?
OR
**b)** Bring `behat/mink` up to date with `minkphp/mink`  (So we can use version 1.7) ?

There has since been many changes done in mink. It would be really nice to have these changes!

**Comment by stof** [comment]
`~1.5` means `>=1.5, <2.0`. So this allows the latest version.

and you are confusing Github URLs with package names. Even though we moved the repo to a separate organization a long time ago, the package name has not changed. So `minkphp/mink` does not exist at all.
