### ISSUE TITLE
ElementNotFound with Firefox 57

### ISSUE THREAD

**Issue by ck-developer** [Behat/MinkExtension#312]
Hello I use selenium with chrome and firefox for functional tests everything. works correctly with chrome but when I run the tests with firefox I always get an ElementNotFound exception. Thanks for your help.

I created this repo https://github.com/ck-developer/symfony-behat to reproduce the behavior.

Selenium: 3.8.1
Firefox: 57.0
Chrome: 62.0.3202.94

**Comment by FlashBytes** [comment]
Hello CK,

this is a long known issue. You might also want to check out:

https://github.com/Behat/MinkExtension/issues/307

The latest version I can use with Mink/Behat and Selenium 3 is version FF 49.

All the Best

**Comment by leymannx** [comment]
Similar here.

```bash
$ firefox --version
Mozilla Firefox 63.0.1
```

Works fine with Chrome but with Firefox my tests fail.

```bash
Then I should see "Home"                        # Drupal\DrupalExtension\Context\MinkContext::assertPageContainsText()
      Element not found with xpath, //html
       (WebDriver\Exception\NoSuchElement)
```

or

```bash
And I fill in "name" with "foo"                            # Drupal\DrupalExtension\Context\MinkContext::fillField()
      Form field with id|name|label|value|placeholder "name" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

Refs https://github.com/mozilla/geckodriver/issues/1216#issuecomment-398107280

But no fix found so far.

**Comment by stof** [comment]
MinkSelenium2Driver does not yet support the W3C webdriver protocol. There are discussions about it (see https://github.com/minkphp/MinkSelenium2Driver/issues/293)

geckodriver implements only the W3C protocol, not the JsonWire one, so it is not compatible currently.

i'm closing this issue, as MinkExtension does not have an issue.

**Comment by leymannx** [comment]
Uh, thanks for the insights! I finally see the bottom of that issue after a half a day of investigation.

@stof – Does the same apply for this issue https://github.com/Behat/MinkExtension/issues/307 as well?

**Comment by stof** [comment]
@leymannx yes. Thanks for the heads up on that other issue. I also closed it referencing the Mink discussion.
