### ISSUE TITLE
Installation issue (conflict with symfony/css-selector)

### ISSUE THREAD

**Issue by fabienlem** [Behat/MinkExtension#332]
Hello there!

I'm reporting an issue when installing MinkExtension with Symfony 4.1.1.

I proceed with this command: ```composer req behat/behat --dev```.

But I got the following message as ```symfony/css-selector``` is not supported.

```
    - Conclusion: don't install behat/mink v1.7.1
    - Conclusion: remove symfony/css-selector v4.1.1
    - Installation request for behat/mink ^1.7 -> satisfiable by behat/mink[v1.7.0, v1.7.1].
    - Conclusion: don't install symfony/css-selector v4.1.1
    - behat/mink v1.7.0 requires symfony/css-selector ~2.1 
```

Is there a workaround?

Thank you for your help!

Regards,

Fabien

**Comment by fabienlem** [comment]
Ok guys,

I fixed this by downgrading ```symfony/css-selector``` package as follow:

```Updating symfony/css-selector (v4.1.1 => v3.4.12): Downloading (100%)```

I close this issue, my thought is that's a DX issue.

Regards,

Fabien

**Comment by gustawdaniel** [comment]
But problem is not solved

```
composer require --dev behat/mink-extension --verbose
Using version ^2.3 for behat/mink-extension
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.2.*"
Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - behat/mink-extension 2.3.0 requires behat/mink ^1.5 -> satisfiable by behat/mink[v1.5.0, v1.6.0, v1.6.1, v1.7.0, v1.7.1].
    - behat/mink-extension 2.3.1 requires behat/mink ^1.5 -> satisfiable by behat/mink[v1.5.0, v1.6.0, v1.6.1, v1.7.0, v1.7.1].
    - behat/mink v1.7.1 requires symfony/css-selector ~2.1|~3.0 -> no matching package found.
    - behat/mink v1.7.0 requires symfony/css-selector ~2.1 -> no matching package found.
    - behat/mink v1.6.1 requires symfony/css-selector ~2.0 -> no matching package found.
    - behat/mink v1.6.0 requires symfony/css-selector ~2.0 -> no matching package found.
    - behat/mink v1.5.0 requires symfony/css-selector ~2.0 -> no matching package found.
    - Installation request for behat/mink-extension ^2.3 -> satisfiable by behat/mink-extension[2.3.0, 2.3.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

I have `symfony/css-selector (v4.2.8)` and do not want to downgrade. 

Symfony 4 compatibility was merged here https://github.com/Behat/MinkExtension/pull/308

but problem is probably not here but with `behat/mink` package.

**Comment by gustawdaniel** [comment]
This was solved in 

https://github.com/minkphp/Mink/commit/808702de1a3bebbd97a9339790e313e2aa7525ee#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

now in master file https://github.com/minkphp/Mink/blob/master/composer.json contains `symfony/css-selector v4`

but has own version `"dev-master": "1.7.x-dev"`

So we can see that blocking issues are:

https://github.com/minkphp/MinkSelenium2Driver/issues/287
https://github.com/minkphp/MinkZombieDriver/issues/182

and blocking pull requests

https://github.com/minkphp/MinkSelenium2Driver/pull/278
https://github.com/minkphp/MinkSelenium2Driver/pull/296
https://github.com/minkphp/MinkZombieDriver/pull/189

**Comment by gustawdaniel** [comment]
For now workaround:

add line 

```
  "minimum-stability": "dev"
```

to root of `composer.json`

https://getcomposer.org/doc/04-schema.md#minimum-stability
