### ISSUE TITLE
Support for Symfony 5.x

### ISSUE THREAD

**Issue by didix16** [Behat/MinkExtension#361]
Hi guys,

Could be possible the compatibility with symfony 5.x configs?

I'm trying to install Laravel 7 which uses symfony 5 components but minkextension is only compatible till symfony 4.

Thanks in advance

**Comment by chadyred** [comment]
I have just done a pull request for this and I am in your same case.

**Comment by chadyred** [comment]
It works like a charm so I wait for merge !

**Comment by didix16** [comment]
Perfect, thank you so much!

**Comment by chadyred** [comment]
You could use this branch if you want : `cdaguerre:sf-5-compat`. Their are 2 other PR on this subjet, I close mine in favorite of this one : https://github.com/Behat/MinkExtension/issues/361 !

**Comment by didix16** [comment]
Ok, thanks. I'll try to use that branch. Let's see if it works with my project :)

**Comment by AmokraneMancer** [comment]
Is any one has a solution to make it run on Symfony 5.x ?

**Comment by chadyred** [comment]
Like this to resolve on my github repo that fix this dependencies:

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/chadyred/MinkExtension"
        }
    ],
    "require-dev": {
        "behat/mink-extension": "dev-upgrade/allow-symony-5 as 2.3",
    }
}
```

**Comment by chadyred** [comment]
@AmokraneMancer  up

**Comment by AmokraneMancer** [comment]
Thank you so much @chadyred. it works perfectly !

**Comment by chadyred** [comment]
You're welcome !

**Comment by much-rebel** [comment]
Can't make it work as @chadyred suggested:

```
# composer.json
"require-dev": {
    "behat/mink-extension": "dev-upgrade/allow-symony-5 as 2.3",
...
# CLI
$: composer-2 update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Restricting packages listed in "symfony/symfony" to "5.4.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires behat/mink-extension dev-upgrade/allow-symony-5 as 2.3, found behat/mink-extension[dev-master, v1.0.0, ..., 1.3.x-dev, v2.0.0, ..., 2.x-dev (alias of dev-master)] but it does not match the constraint.
```

**Comment by chadyred** [comment]
Did you add this in your `composer.json`

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/chadyred/MinkExtension"
        }
    ],
```

**Comment by much-rebel** [comment]
I tried that with no luck tho. In the end I've switched to https://github.com/FriendsOfBehat/MinkExtension which works just fine without the need of aliasing and stuff.

**Comment by chadyred** [comment]
You are right, this is the best way as the https://github.com/FriendsOfBehat/MinkExtension  is the main repository for MinkExtension and the maintain repository
