### ISSUE TITLE
Improved form handling

### ISSUE THREAD

**Issue by lphuberdeau** [Behat/MinkExtension#40]
This is more of a feature request.

I have ran into a situation where getting to write the test fixture is harder than it should. I am working to write functional tests on a legacy application using Selenium WebDriver and Behat.

I often run into situations where the tests would look like this:

```
Given I am authenticated as "..."
When I fill "abc" with "123"
And I press "Go"
Then ...
```

The issue is that the page contains the Go label on multiple buttons and there is no other constant field I can rely on for the button. IDs are being auto-generated and the other values are not constant. Modifying the application to change these is not an option. We're trying to get there, but Behat is part of the transition process.

There is a simple heuristic for this. Before searching for the whole page for the button, begin by searching in the form the last input was filled in.

I implemented this locally in my FeatureContext, but I feel it would be useful for more people. The implementation I have is not so clean as I ran into several issues while implementing it.

Among others:
* Identity is not preserved when using getParent()
* Lookup has to be re-implemented in fillField() and pressButton() as it is entirely delegated to Mink, which does not provide the field back.

**Comment by stof** [comment]
The issue with this proposal is that it suggests making the feature context stateful, changing the behavior steps based on the outcome of the previous steps. This looks wrong to me. Thus, doing this change in existing steps would be a BC break.

Performing such logic in custom steps is the preferred option IMO (and an even better option is to avoid using builtin MinkContext steps and use steps defined based on the language of your business).

I'm closing this issue as Won't fix.
