### ISSUE TITLE
Exception thrown by (//html/.//*[self::input ..

### ISSUE THREAD

**Issue by sensorario** [Behat/MinkExtension#89]
I've these two steps:

```
    Then the response should contain "LoginForm_username"
    And I fill in "LoginForm_username" with "ugolupo"
```

The first one works. The second, ... no.
I get this exception:

And I fill in "LoginForm_username" with "ugolupo"               # FeatureContext::fillField()
      Exception thrown by (//html/.//_[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')][(((./@id = 'LoginForm_username' or ./@name = 'LoginForm_username') or ./@id = //label[contains(normalize-space(string(.)), 'LoginForm_username')]/@for) or ./@placeholder = 'LoginForm_username')] | .//label[contains(normalize-space(string(.)), 'LoginForm_username')]//.//_[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')])[1]
      Form submit button for field with xpath "(//html/.//_[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')][(((./@id = 'LoginForm_username' or ./@name = 'LoginForm_username') or ./@id = //label[contains(normalize-space(string(.)), 'LoginForm_username')]/@for) or ./@placeholder = 'LoginForm_username')] | .//label[contains(normalize-space(string(.)), 'LoginForm_username')]//.//_[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')])[1]"not found.

My composer is:

```
"require": {
    "behat/behat": "2.4.*@stable",
    "behat/mink": "1.4.*@stable",
    "behat/mink-extension": "*",
    "behat/mink-goutte-driver": "*",
    "behat/mink-selenium2-driver": "*"
},
"minimum-stability": "dev",
"config": {
    "bin-dir": "bin/"
}
```

**Comment by arnoa69** [comment]
Hi, probably you have firefox higher than 33. I had the same problem. Then downgrading worked, but ff did automatic update again even though in about:config, updates were turned off. I switched over to google chrome, with the chromedriver and it woks like a charme now.

**Comment by aik099** [comment]
The generated Xpath was changed in Mink 1.6. Maybe this will fix the problem.
