### ISSUE TITLE
Selenium2Driver maximize window capability

### ISSUE THREAD

**Issue by kwisatz** [Behat/MinkExtension#90]
I was wondering whether there was a possibility to get selenium to maximize browser windows using the capabilities configuration parameter in behat.yml?

I've been looking at the Extension.php file which doesn't define any such capability, while selenium does. See http://selenium.googlecode.com/svn/trunk/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#selenium.webdriver.remote.webdriver.WebDriver.maximize_window

Or is there any other way to get selenium to maximize my browser windows should they (for whatever reason) choose not to start fully maximized?

**Comment by sakonachhoeurng** [comment]
@stof I have problem now with selenium 3.6.0 and google chrome version 62.X
`Webdriver http error: 404, payload :unknown command: session/a7da7718cb5f9dc317dd29c29dd5c4f8/window/maximize (WebDriver\Exception\CurlExec)
`
Can you help for this?

**Comment by spolischook** [comment]
@sakonachhoeurng try to update chromedriver to version 2.33

**Comment by sakonachhoeurng** [comment]
@spolischook, I already update to latest chromedriver 2.33, I think the main problem come from selenium version 3.6.0

**Comment by spolischook** [comment]
@sakonachhoeurng you can skip selenium at all, as recent version chromedriver implement selenium api and can work alone without selenium
